# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesskey', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=200)),
            ],
        ),
    ]
